config/routes.rb
Rails.application.routes.draw do

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  resources :events, except: [:index] do

    resources :groups do
      resources :guests
    end

    resources :photos
    resources :venue_photos

    resources :task_lists do
      resources :tasks
    end

    resources :guests
    resources :groups do
      put 'rsvp', on: :collection
      resources :guests
    end
  end

  namespace :admin do
    resources :events, except: [:index] do
      resources :sections
      resources :guests, except: [:show]
      resources :groups
    end
    root "admin#dashboard"
  end

  resources :photos, :only => [:index, :create, :destroy]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "events#show"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :groups
  has_many :guests
  has_many :photos
  has_many :sections
  has_many :task_lists
  has_many :tasks
  has_many :venue_photos
  has_many :event_notifications

  after_create :create_event_task_list

  def days_to_go
    (Event.last.date - Date.today).to_int.clamp(0, Float::INFINITY)
  end

  def formatted_time
    date.strftime("%A #{date.day.ordinalize} %B %Y")
  end

  def show_rsvp?
    return true if Rails.env == "development"
    return false if in_past?
    return false if is_today?
    return true
  end

  def in_past?
    date < Date.today
  end

  def is_today?
    date == Date.today
  end

  def show_photos?(params)
    return true if params[:development]
    return true if Rails.env == "development"
    return true if in_past?
    return true if is_today?
    return false
  end

  def self.send_notifications(id)
    find(id).send_notifications
  end

  def send_notifications
    rsvps = Event.first.event_notifications.where(notification_type: "rsvp")
    photos = Event.first.event_notifications.where(notification_type: "photo_upload")
    unless rsvps.empty? and photos.empty?
      if EventMailer.notifications(rsvps, photos).deliver
        rsvps.destroy_all
        photos.destroy_all
      end
    end
  end

  private

  def create_event_task_list
    TaskList.create({event_id: id})
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :set_event, only: [:show, :update]
  before_filter :set_groups, only: [:show]

  def show
    @group = Group.new
    @primary_venue_photo = VenuePhoto.find(@event.primary_venue_photo).file_url unless @event.primary_venue_photo.nil?
    @venue_photos = VenuePhoto.where.not(id: @event.primary_venue_photo) || []
  end

  def update
    @event.update_attributes(event_params)
    redirect_to :back
  end

  private

  def set_event
    @event = Event.find params[:id] || default_event
  end

  def event_params
    params.require(:event).permit(:date, :location, :active, :title, :primary_venue_photo)
  end

  def set_groups
    @groups = @event.groups
  end
end

app/views/events/_form.haml
= simple_form_for @event do |f|
  = f.input :title
  = f.input :location
  = f.input :venue_body, input_html: {rows: 10}
  = f.input :venue_directions, input_html: {rows: 10}
  = f.input :date, as: :string, input_html: { class: "js-datetimepicker" }
  = f.button :submit

app/views/events/show.haml
= content_for :title, "#{@event.partner_one} & #{@event.partner_two} Wedding - #{@event.formatted_time}"

.box.box--mint
  .row
    .column.small-12
      %h1
        = @event.partner_one
        %span.font--pacifico &
        = @event.partner_two
.row
  .column.small-12
    %h5 Get married on
    %h3= @event.formatted_time

#location.inverted.paralax{ :style => "background-image: url('#{@primary_venue_photo}');" }
  .row
    .column.small-12
      %br
      %br
      %br

      %h2= "at the beautiful #{@event.venue_name}"
      %h4= "in #{@event.venue_address_city}"

      %br
      %br
      %br

      - if @event.show_rsvp?
        = link_to raw("<span class='icon icon-pencil'></span> RSVP now"), "#rsvp", class: "button large js-scroll-to"

- if @event.show_rsvp?
  %br

  #rsvp.row{ng: { controller: "RsvpController" }}
    .column.small-12
      %h5 RSVP
      = simple_form_for rsvp_event_groups_path(@event) do |f|
        %h3 Step one - enter your name
        .row
          .column.small-12.column.medium-6.medium-offset-3
            = f.input :guest, collection: @groups, as: :select, placeholder: "Select your name(s)"
        %br

      .row
        .column.small-12.medium-6{ "ng-repeat" => "guest in group" }
          .card
            %h3 {{ guestName(guest) }}
            %input{type: "text", placeholder: "enter guest name", ng: { show: "guest.is_guest", model: "newGuest.name" }}
            %p {{ rsvpStatus(guest) }}
            %span.button{ng: { show: "guest.rsvp == null && !guest.is_guest", click: "setRsvp(guest, false)"}} Sorry I can not attend
            %span.button{ng: { hide: "guest.is_guest || guest.rsvp", click: "setRsvp(guest, true)"}} {{ rsvpButtonText(guest) }}
            %span.button{ng: { show: "guest.rsvp", click: "setRsvp(guest, false)"}} Sorry I can no longer make it
            %span.button{ng: { show: "guest.is_guest", disabled: "newGuest.name == ''", click: "defineGuest(guest)"}} {{ rsvpButtonText(guest) }}

            .reset{ng: {show: "guest.rsvp && guest.invited_to_ceremony"}}
              %label
                %input{type: "checkbox", ng: {change: "toggleVegetarian(guest)", model: "guest.vegetarian"}}
                Vegetarian

.box.box--mint
  .row
    .column.small-12
      %h5 Venue

  .row-fluid.overflow
    %ul.small-block-grid-3
      - @venue_photos.first(3).each do |venue_photo|
        %li= image_tag venue_photo.file_url

  .row
    .column.small-12
      #venue-copy
        %h3= @event.venue_name
        = raw(@event.venue_body.from_markdown_to_html)
        %br
        %h4 Directions
        = raw(@event.venue_directions.from_markdown_to_html)
        %br
        .map--overlay{onclick: "style.pointerEvents='none'"}
        :plain
          <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
          <div class="map wpgmappity_container" id="wpgmappitymap"></div>
          <script type="text/javascript">
          (function(){
          function wpgmappity_maps_loaded() {
          var latlng = new google.maps.LatLng(51.456370, -2.606592);
          var options = {
           center : latlng,
           mapTypeId: google.maps.MapTypeId.ROADMAP,
           zoomControl : true,
           zoomControlOptions :
           {
           style: google.maps.ZoomControlStyle.SMALL,
           position: google.maps.ControlPosition.TOP_LEFT
           },
           mapTypeControl : false,
           scaleControl : false,
           streetViewControl : false,
           panControl : false, zoom : 14
          };
          var wpgmappitymap = new google.maps.Map(document.getElementById('wpgmappitymap'), options);
          var point0 = new google.maps.LatLng(51.4606887,-2.6247733000000153);
          var marker0= new google.maps.Marker({
           icon : 'http://labio-wedding.s3.amazonaws.com/assets/church7.png',
           position : point0,
           map : wpgmappitymap
           });
          google.maps.event.addListener(marker0,'click',
           function() {
           var infowindow = new google.maps.InfoWindow(
           {content: '<h3 class="font-book-antiqua">The Mansion House</h3>'});
           infowindow.open(wpgmappitymap,marker0);
           });
          var point1 = new google.maps.LatLng(51.4527825,-2.62524099999996);
          var marker1= new google.maps.Marker({
           icon : 'http://labio-wedding.s3.amazonaws.com/assets/hotel39.png',
           position : point1,
           map : wpgmappitymap
           });
          google.maps.event.addListener(marker1,'click',
           function() {
           var infowindow = new google.maps.InfoWindow(
           {content: '<h3 class="font-book-antiqua">The Bristol Hotel</h3><a target=\"_blank\" href=\"http://www.doylecollection.com/hotels/the-bristol-hotel\">Go to website</a>'});
           infowindow.open(wpgmappitymap,marker1);
           });
          var point2 = new google.maps.LatLng(51.4488666,-2.587721999999985);
          var marker2= new google.maps.Marker({
           icon : 'http://labio-wedding.s3.amazonaws.com/assets/hotel39.png',
           position : point2,
           map : wpgmappitymap
           });
          google.maps.event.addListener(marker2,'click',
           function() {
           var infowindow = new google.maps.InfoWindow(
           {content: '<h3 class="font-book-antiqua">DoubleTree</h3><a target=\"_blank\" href=\"http://doubletree3.hilton.com/en/index.html\">Go to website</a>'});
           infowindow.open(wpgmappitymap,marker2);
           });
          var point3 = new google.maps.LatLng(51.4559676,-2.5847842000000583);
          var marker3= new google.maps.Marker({
           icon : 'http://labio-wedding.s3.amazonaws.com/assets/hotel39.png',
           position : point3,
           map : wpgmappitymap
           });
          google.maps.event.addListener(marker3,'click',
           function() {
           var infowindow = new google.maps.InfoWindow(
           {content: '<h3 class="font-book-antiqua">Bristol Marriott</h3><a target=\"_blank\" href=\"http://www.marriott.com/hotels/travel/brsdt-bristol-marriott-hotel-city-centre/\">Go to website</a>'});
           infowindow.open(wpgmappitymap,marker3);
           });
          var point4 = new google.maps.LatLng(51.4522431,-2.59696770000005);
          var marker4= new google.maps.Marker({
           icon : 'http://labio-wedding.s3.amazonaws.com/assets/hotel39.png',
           position : point4,
           map : wpgmappitymap
           });
          google.maps.event.addListener(marker4,'click',
           function() {
           var infowindow = new google.maps.InfoWindow(
           {content: '<h3 class="font-book-antiqua">Radisson Blu</h3><a target=\"_blank\" href=\"http://www.radissonblu.co.uk/hotel-bristol\">Go to website</a>'});
           infowindow.open(wpgmappitymap,marker4);
           });
          var point5 = new google.maps.LatLng(51.4597989,-2.586416399999962);
          var marker5= new google.maps.Marker({
           icon : 'http://labio-wedding.s3.amazonaws.com/assets/hotel39.png',
           position : point5,
           map : wpgmappitymap
           });
          google.maps.event.addListener(marker5,'click',
           function() {
           var infowindow = new google.maps.InfoWindow(
           {content: '<h3>Holiday Inn</h3><a target=\"_blank\" href=\"http://www.ihg.com/holidayinn/hotels/gb/en/bristol/brscc/hoteldetail\">Go to website</a>'});
           infowindow.open(wpgmappitymap,marker5);
           });
          }
          window.onload = function() {
           wpgmappity_maps_loaded();
          };
          })()
          </script>

  %br

  #ballons
    #balloon01{data: {top: {bottom: "top: -150px"}, bottom: {center: "top: 200px"}}}
    #balloon02{data: {top: {bottom: "top: -200px"}, bottom: {center: "top: 350px"}}}
    #balloon03{data: {top: {bottom: "top: -50px"}, bottom: {center: "top: 230px"}}}
  #bridge
    #couple

- @event.sections.each do |section|
  %section
    .row
      .column.small-12.medium-8.medium-offset-2
        %h5= section.title
        = raw(section.content.from_markdown_to_html)


%br

.row
  .column.small-12.medium-8.medium-offset-2
    %h5 Photos

- if @event.show_photos?(params)
  = render partial: "photos/form"
  = render partial: "photos/index"
  #modalDropImages.reveal-modal{"data-reveal" => "", :style => "display: block;"}
    %h2.text--salmon Drop images to upload
- else
  .row
    .column.small-12
      %p We invite you back to this website after the wedding to view and upload photos

%br

%footer
  %p
    %small
      For our techie friends hitched.it is an
      %a{:href => "http://github.com/adambutler/wedding-on-rails"} open source project
      built on Ruby-on-Rails.