config/routes.rb
Rails.application.routes.draw do

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  resources :events, except: [:index] do

    resources :groups do
      resources :guests
    end

    resources :photos
    resources :venue_photos

    resources :task_lists do
      resources :tasks
    end

    resources :guests
    resources :groups do
      put 'rsvp', on: :collection
      resources :guests
    end
  end

  namespace :admin do
    resources :events, except: [:index] do
      resources :sections
      resources :guests, except: [:show]
      resources :groups
    end
    root "admin#dashboard"
  end

  resources :photos, :only => [:index, :create, :destroy]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "events#show"

end

app/views/admin/admin/_lists.haml
%h2 Lists

- @event.task_lists.each do |task_list|
  - task_list.tasks.each do |task|
    = render partial: "tasks/form", locals: { event: @event, task_list: task_list, task: task }

app/views/admin/admin/dashboard.haml
= content_for :title, "Dashboard"

%h1 Admin

%ul.small-block-grid-4
  %li
    .panel.text-center
      %h2= @guests.count
      %p= "Guests".pluralize(@guests.count)
      %small
        %span.text--success
          = Guest.attending.count
          Yes
        |
        %span.text--error
          = Guest.not_attending.count
          No
        |
        = Guest.attendance_unknown.count
        Not RSVPd
  %li
    .panel.text-center
      %h2= @groups.count
      %p= "Groups".pluralize(@groups.count)
  %li
    .panel.text-center
      %h2= "£12,345"
      %p= "Estimated Cost"
  %li
    .panel.text-center
      %h2= @event.days_to_go
      %p= "#{"Days".pluralize(@event.days_to_go)} to go"

%dl.tabs{"data-tab" => ""}
  %dd.active
    %a{:href => "#settings"} Settings
  %dd
    %a{:href => "#content"} Content
  %dd
    %a{:href => "#todos"} To Do's
  %dd
    %a{:href => "#venue"} Venue
  %dd
    %a{:href => "#guests"} Guests
.tabs-content
  #settings.content.active
    - if @guests.empty?
      %p.alert
        You havn't added any guests yet. Why not #{link_to "add some now", new_guest_path}?
    - else
      = render partial: "events/form"

  #content.content
    %table
      %thead
        %tr
          %th Title
          %th Actions
      %tbody
        - @event.sections.each do |section|
          %tr
            %td= section.title
            %td
              = link_to "edit", edit_admin_event_section_path(@event, section)
              = link_to "delete", admin_event_section_path(@event, section), data: { confirm: "Are you sure you want to delete this section?" }, method: :delete

    = render partial: "admin/sections/form"

  #todos.content
    = render partial: "lists"
  #venue.content
    = render partial: "venue_photos/index"
    = render partial: "venue_photos/form"
  #guests.content
    %table
      %thead
        %tr
          %th Guests
          %th RSVP'd
          %th Actions
      %tbody
        - @groups.each do |group|
          %tr
            %td= group.title
            %td
              - group.guests.each do |guest|
                = guest.rsvp
            %td
              = link_to "edit", edit_admin_event_group_path(@event, group)
              = link_to "delete", admin_event_group_path(@event, group), data: { confirm: "Are you sure you want to delete this group of guests?" }, method: :delete
    = link_to "New Guest", new_admin_event_guest_path(@event)